// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ItAcademy.Demo.ClassWork.Client.Mvc.Controllers
{
    public partial class TryUpdateModelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TryUpdateModelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TryUpdateModelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IndexV1()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexV1);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IndexInclude()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexInclude);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IndexExclude()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexExclude);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TryUpdateModelController Actions { get { return MVC.TryUpdateModel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "TryUpdateModel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "TryUpdateModel";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string IndexV1 = "IndexV1";
            public readonly string IndexV2 = "IndexV2";
            public readonly string IndexV3 = "IndexV3";
            public readonly string IndexInclude = "IndexInclude";
            public readonly string IndexExclude = "IndexExclude";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string IndexV1 = "IndexV1";
            public const string IndexV2 = "IndexV2";
            public const string IndexV3 = "IndexV3";
            public const string IndexInclude = "IndexInclude";
            public const string IndexExclude = "IndexExclude";
        }


        static readonly ActionParamsClass_IndexV1 s_params_IndexV1 = new ActionParamsClass_IndexV1();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexV1 IndexV1Params { get { return s_params_IndexV1; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexV1
        {
            public readonly string personViewModel = "personViewModel";
            public readonly string studentViewModel = "studentViewModel";
        }
        static readonly ActionParamsClass_IndexInclude s_params_IndexInclude = new ActionParamsClass_IndexInclude();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexInclude IndexIncludeParams { get { return s_params_IndexInclude; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexInclude
        {
            public readonly string studentViewModel = "studentViewModel";
        }
        static readonly ActionParamsClass_IndexExclude s_params_IndexExclude = new ActionParamsClass_IndexExclude();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexExclude IndexExcludeParams { get { return s_params_IndexExclude; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexExclude
        {
            public readonly string studentViewModel = "studentViewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TryUpdateModelController : ItAcademy.Demo.ClassWork.Client.Mvc.Controllers.TryUpdateModelController
    {
        public T4MVC_TryUpdateModelController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexV1Override(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.PersonViewModel personViewModel, ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexV1(ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.PersonViewModel personViewModel, ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexV1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personViewModel", personViewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "studentViewModel", studentViewModel);
            IndexV1Override(callInfo, personViewModel, studentViewModel);
            return callInfo;
        }

        [NonAction]
        partial void IndexV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexV2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexV2);
            IndexV2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexV3Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexV3()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexV3);
            IndexV3Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexIncludeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexInclude(ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexInclude);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "studentViewModel", studentViewModel);
            IndexIncludeOverride(callInfo, studentViewModel);
            return callInfo;
        }

        [NonAction]
        partial void IndexExcludeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexExclude(ItAcademy.Demo.ClassWork.Client.Mvc.Models.TryUpdateModel.StudentViewModel studentViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexExclude);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "studentViewModel", studentViewModel);
            IndexExcludeOverride(callInfo, studentViewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
