// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ItAcademy.Demo.ClassWork.Client.Mvc.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetByNameWithRole()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetByNameWithRole);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult NoWhiteSpacesValidate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NoWhiteSpacesValidate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetByNameWithRole = "GetByNameWithRole";
            public readonly string Create = "Create";
            public readonly string CreateV2 = "CreateV2";
            public readonly string NoWhiteSpacesValidate = "NoWhiteSpacesValidate";
            public readonly string CreateV3 = "CreateV3";
            public readonly string CreateAjax = "CreateAjax";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetByNameWithRole = "GetByNameWithRole";
            public const string Create = "Create";
            public const string CreateV2 = "CreateV2";
            public const string NoWhiteSpacesValidate = "NoWhiteSpacesValidate";
            public const string CreateV3 = "CreateV3";
            public const string CreateAjax = "CreateAjax";
        }


        static readonly ActionParamsClass_GetByNameWithRole s_params_GetByNameWithRole = new ActionParamsClass_GetByNameWithRole();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetByNameWithRole GetByNameWithRoleParams { get { return s_params_GetByNameWithRole; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetByNameWithRole
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CreateV2 s_params_CreateV2 = new ActionParamsClass_CreateV2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateV2 CreateV2Params { get { return s_params_CreateV2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateV2
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_NoWhiteSpacesValidate s_params_NoWhiteSpacesValidate = new ActionParamsClass_NoWhiteSpacesValidate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NoWhiteSpacesValidate NoWhiteSpacesValidateParams { get { return s_params_NoWhiteSpacesValidate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NoWhiteSpacesValidate
        {
            public readonly string LastName = "LastName";
        }
        static readonly ActionParamsClass_CreateV3 s_params_CreateV3 = new ActionParamsClass_CreateV3();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateV3 CreateV3Params { get { return s_params_CreateV3; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateV3
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CreateAjax s_params_CreateAjax = new ActionParamsClass_CreateAjax();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateAjax CreateAjaxParams { get { return s_params_CreateAjax; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateAjax
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Create = "Create";
                public readonly string CreateAjax = "CreateAjax";
                public readonly string CreateAjaxPartial = "CreateAjaxPartial";
                public readonly string CreateV1 = "CreateV1";
                public readonly string CreateV2 = "CreateV2";
                public readonly string CreateV2Client = "CreateV2Client";
                public readonly string CreateV3 = "CreateV3";
                public readonly string Index = "Index";
            }
            public readonly string Create = "~/Views/User/Create.cshtml";
            public readonly string CreateAjax = "~/Views/User/CreateAjax.cshtml";
            public readonly string CreateAjaxPartial = "~/Views/User/CreateAjaxPartial.cshtml";
            public readonly string CreateV1 = "~/Views/User/CreateV1.cshtml";
            public readonly string CreateV2 = "~/Views/User/CreateV2.cshtml";
            public readonly string CreateV2Client = "~/Views/User/CreateV2Client.cshtml";
            public readonly string CreateV3 = "~/Views/User/CreateV3.cshtml";
            public readonly string Index = "~/Views/User/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserController : ItAcademy.Demo.ClassWork.Client.Mvc.Controllers.UserController
    {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetByNameWithRoleOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetByNameWithRole(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetByNameWithRole);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            GetByNameWithRoleOverride(callInfo, name);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateV2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateV2);
            CreateV2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV2 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateV2(ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV2 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateV2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateV2Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void NoWhiteSpacesValidateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string LastName);

        [NonAction]
        public override System.Web.Mvc.JsonResult NoWhiteSpacesValidate(string LastName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NoWhiteSpacesValidate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "LastName", LastName);
            NoWhiteSpacesValidateOverride(callInfo, LastName);
            return callInfo;
        }

        [NonAction]
        partial void CreateV3Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateV3()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateV3);
            CreateV3Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateV3Override(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV3 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateV3(ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV3 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateV3);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateV3Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateAjaxOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateAjax()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateAjax);
            CreateAjaxOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateAjaxOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV2 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateAjax(ItAcademy.Demo.ClassWork.Client.Mvc.Models.EntityFramework.UserViewModelV2 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateAjax);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateAjaxOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
